---
- name: nginx - install
  sudo: yes
  apt: name=nginx

- name: nginx - upload nginx conf
  sudo: yes
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/{{ django_project_name }}

- name: nginx - restart
  sudo: yes
  shell: service nginx restart
