---
- name: virtualenv - create folders
  raw: mkdir -p ~/tmp

- name: virtualenv - install setuptools
  sudo: yes
  apt: name=python-setuptools

- name: virtualenv - install pip
  sudo: yes
  easy_install: name=pip
  when: python_main_version == 2

- name: virtualenv - install pip3
  sudo: yes
  apt: name=python3-pip
  when: python_main_version == 3

- name: virtualenv - install
  sudo: yes
  pip: name=virtualenv

- name: virtualenv - install virtualenvwrapper
  sudo: yes
  pip: name=virtualenvwrapper

- name: virtualenv - add virtualenvwrapper exports to .bash_profile
  lineinfile: 'dest=~/.bash_profile line="{{ item }}" create=yes'
  with_items:
    - export PATH=$PATH:$HOME/bin
    - export TMPDIR=$HOME/tmp
    - export WORKON_HOME=/home/{{ user }}/Envs
    - export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python{{ python_main_version}}.{{ python_sub_version }}
    - export PIP_VIRTUALENV_BASE=$WORKON_HOME
    - export PIP_RESPECT_VIRTUALENV=true
    - source /usr/local/bin/virtualenvwrapper.sh

- name: virtualenv - source the new .bashrc
  raw: source .bashrc
