---
- name: common-python - install global packages
  sudo: yes
  pip: name={{ item.name }}
  with_items:
    - { name: ipython }
    - { name: psycopg2 }
    - { name: python-memcached }

- name: common-python - update distutils
  sudo: yes
  raw: easy_install distribute
