---
- name: common-python - install global packages
  remote_user: root
  pip: name={{ item.name }}
  with_items:
    - { name: ipython }
    - { name: psycopg2 }
    - { name: python-memcached }

- name: common-python - update distutils
  remote_user: root
  sudo: yes
  raw: pip install distribute --upgrade
