---
- name: prerequisites - add authorized_keys
  template: src=authorized_keys dest=~/.ssh/

- name: prerequisites - chmod authorized_keys
  raw: chmod 600 ~/.ssh/authorized_keys && chmod 700 ~/.ssh
