---
- name: prerequisites - update locale
  sudo: yes
  raw: locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8

- name: prerequisites - make ssh folder
  raw: mkdir -p ~/.ssh

- name: prerequisites - create ssh key
  user: name={{ user }} generate_ssh_key=yes
