---
- name: common - install packages
  sudo: yes
  apt: pkg={{ item }} update_cache=yes state=latest cache_valid_time=4320
  with_items:
    - curl
    - g++
    - gettext
    - git-core
    - libsqlite3-dev
    - build-essential
    - libssl-dev
    - libffi-dev
    - make
    - mercurial
    - python-dev
    - sqlite3
    - vim
    - libjpeg-dev
