---
- name: letsencrypt - prepare
  sudo: yes
  apt:
    name: software-properties-common
    update_cache: yes
    
- name: letsencrypt - add certbot repository
  sudo: yes
  raw: add-apt-repository ppa:certbot/certbot

- name: letsencrypt - install certbot
  sudo: yes
  apt:
    name: python-certbot-nginx
    update_cache: yes

- name: letsencrypt - create folders
  shell: mkdir -p /home/{{ user }}/letsencrypt

- name: letsencrypt - get cert
  shell: certbot --nginx certonly -w /home/{{ user }}/letsencrypt --agree-tos -n -d {{ domain }} -d www.{{ domain }} --email={{ email }}
  sudo: yes

- name: letsencrypt - create DH group
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  sudo: yes

- name: letsencrypt - cron cert renewal
  cron:
    name: "renew cert"
    minute: "30"
    hour: "2"
    weekday: "1"
    job: "certbot renew >> /var/log/le-renew.log"

- name: letsencrypt - update nginx conf
  sudo: yes
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/{{ django_project_name }}


- name: letsencrypt - nginx restart
  sudo: yes
  shell: service nginx restart
